Test deployment event

diff --git a/tests/fixtures/hello b/tests/fixtures/hello
--- a/tests/fixtures/hello
+++ b/tests/fixtures/hello
@@ -1,3 +1,12 @@
 #!/bin/bash
 
-echo Hello
+if [ $# -eq 0 ]; then
+  echo Hello
+else
+  if [ "$1" = "--version" ]; then
+    echo "$(basename "$0") v.1.0"
+  else
+    >&2 echo "Error: Don't know what to do with $@"
+    exit 1
+  fi
+fi
